version: "3.8"

services:
  app:
    image: alpine/java:21-jre
    container_name: dragon_request_back
    ports:
      - "8080:8080"
    volumes:
      - ./infrastructure/build/libs/infrastructure-1.0-SNAPSHOT.jar:/app/dragon-request.jar
    command: ["java", "-jar", "/app/dragon-request.jar"]
